package moviegamegui;

import moviegamecore.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Stephen
 */
public class MovieGameGUI extends javax.swing.JFrame
{
    //attributes
    
    //links
    private GameCoord game;

    
    //constructors
    
    /**
     * Creates new form MovieGameGUI
     */
    public MovieGameGUI()
    {
        //create a new game
        game = new GameCoord();
        
        initComponents();
        
        // Initialise all the list components
        actorsList.setListData(game.getActors());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        setupScreenPanel = new javax.swing.JPanel();
        setupLabel = new javax.swing.JLabel();
        addMovieLabel = new javax.swing.JLabel();
        addPlayerLabel = new javax.swing.JLabel();
        moviesInGameLabel = new javax.swing.JLabel();
        listOfActorsLabel = new javax.swing.JLabel();
        addMovieTextField = new javax.swing.JTextField();
        addPlayerTextField = new javax.swing.JTextField();
        addMovieSubmitButton = new javax.swing.JButton();
        addPlayerSubmitButton = new javax.swing.JButton();
        updateMoviesInGameButton = new javax.swing.JButton();
        displayActorsInMovieSubmitButton = new javax.swing.JButton();
        displayPlayersInGameSubmitButton = new javax.swing.JButton();
        initialiseSubmitButton = new javax.swing.JButton();
        addActorToMovieSubmitutton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        moviesList = new m256gui.M256JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        actorsList = new m256gui.M256JList();
        gameScreenPanel = new javax.swing.JPanel();
        playRoundButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        playersList = new m256gui.M256JList();
        playersLabel = new javax.swing.JLabel();
        lowerLevelPanel = new javax.swing.JPanel();
        roundNoLabel = new javax.swing.JLabel();
        movieTitleLabel = new javax.swing.JLabel();
        roundNoTextfield = new javax.swing.JTextField();
        movieTitleTextfield = new javax.swing.JTextField();
        playerAnswerSubmitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        name1Textfield = new javax.swing.JTextField();
        name2Textfield = new javax.swing.JTextField();
        name3Textfield = new javax.swing.JTextField();
        name4Textfield = new javax.swing.JTextField();
        name5Textfield = new javax.swing.JTextField();
        name6Textfield = new javax.swing.JTextField();
        name7Textfield = new javax.swing.JTextField();
        name8Textfield = new javax.swing.JTextField();
        name9Textfield = new javax.swing.JTextField();
        name10Textfield = new javax.swing.JTextField();
        name11Textfield = new javax.swing.JTextField();
        name12Textfield = new javax.swing.JTextField();
        name13Textfield = new javax.swing.JTextField();
        name14Textfield = new javax.swing.JTextField();
        name15Textfield = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        updateTableSubmitButton = new javax.swing.JButton();
        SharedPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));

        jTabbedPane1.setBackground(new java.awt.Color(153, 204, 255));

        setupScreenPanel.setBackground(new java.awt.Color(153, 204, 255));
        setupScreenPanel.setLayout(null);

        setupLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setupLabel.setText("Set Up the game");
        setupScreenPanel.add(setupLabel);
        setupLabel.setBounds(150, 10, 1000, 30);

        addMovieLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addMovieLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addMovieLabel.setText("Add Movie:");
        setupScreenPanel.add(addMovieLabel);
        addMovieLabel.setBounds(120, 50, 80, 30);

        addPlayerLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addPlayerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addPlayerLabel.setText("Add Player:");
        setupScreenPanel.add(addPlayerLabel);
        addPlayerLabel.setBounds(720, 50, 80, 30);

        moviesInGameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moviesInGameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moviesInGameLabel.setText("List of movies in game");
        setupScreenPanel.add(moviesInGameLabel);
        moviesInGameLabel.setBounds(180, 100, 210, 30);

        listOfActorsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listOfActorsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listOfActorsLabel.setText("List of actors");
        setupScreenPanel.add(listOfActorsLabel);
        listOfActorsLabel.setBounds(420, 100, 330, 30);

        addMovieTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setupScreenPanel.add(addMovieTextField);
        addMovieTextField.setBounds(200, 50, 240, 30);

        addPlayerTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setupScreenPanel.add(addPlayerTextField);
        addPlayerTextField.setBounds(810, 50, 200, 30);

        addMovieSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addMovieSubmitButton.setText("Submit");
        addMovieSubmitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addMovieSubmitButtonActionPerformed(evt);
            }
        });
        setupScreenPanel.add(addMovieSubmitButton);
        addMovieSubmitButton.setBounds(460, 50, 90, 30);

        addPlayerSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addPlayerSubmitButton.setText("Submit");
        addPlayerSubmitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addPlayerSubmitButtonActionPerformed(evt);
            }
        });
        setupScreenPanel.add(addPlayerSubmitButton);
        addPlayerSubmitButton.setBounds(1020, 50, 90, 30);

        updateMoviesInGameButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateMoviesInGameButton.setText("Update");
        updateMoviesInGameButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                updateMoviesInGameButtonActionPerformed(evt);
            }
        });
        setupScreenPanel.add(updateMoviesInGameButton);
        updateMoviesInGameButton.setBounds(250, 400, 90, 30);

        displayActorsInMovieSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayActorsInMovieSubmitButton.setText("Select movie and display actors in movie");
        displayActorsInMovieSubmitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                displayActorsInMovieSubmitButtonActionPerformed(evt);
            }
        });
        setupScreenPanel.add(displayActorsInMovieSubmitButton);
        displayActorsInMovieSubmitButton.setBounds(810, 220, 300, 30);

        displayPlayersInGameSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayPlayersInGameSubmitButton.setText("Display players in the game");
        displayPlayersInGameSubmitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                displayPlayersInGameSubmitButtonActionPerformed(evt);
            }
        });
        setupScreenPanel.add(displayPlayersInGameSubmitButton);
        displayPlayersInGameSubmitButton.setBounds(810, 160, 300, 30);

        initialiseSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        initialiseSubmitButton.setText("Initialise");
        initialiseSubmitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                initialiseSubmitButtonActionPerformed(evt);
            }
        });
        setupScreenPanel.add(initialiseSubmitButton);
        initialiseSubmitButton.setBounds(890, 300, 150, 70);

        addActorToMovieSubmitutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addActorToMovieSubmitutton.setText("Select movie and actor and add actor to movie");
        addActorToMovieSubmitutton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addActorToMovieSubmituttonActionPerformed(evt);
            }
        });
        setupScreenPanel.add(addActorToMovieSubmitutton);
        addActorToMovieSubmitutton.setBounds(420, 400, 330, 30);

        moviesList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(moviesList);

        setupScreenPanel.add(jScrollPane3);
        jScrollPane3.setBounds(200, 130, 180, 260);

        actorsList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(actorsList);

        setupScreenPanel.add(jScrollPane5);
        jScrollPane5.setBounds(420, 130, 330, 260);

        jTabbedPane1.addTab("Set Up Screen", setupScreenPanel);

        gameScreenPanel.setBackground(new java.awt.Color(255, 204, 204));
        gameScreenPanel.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                gameScreenPanelComponentShown(evt);
            }
        });
        gameScreenPanel.setLayout(null);

        playRoundButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playRoundButton.setText("Play Round");
        playRoundButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                playRoundButtonActionPerformed(evt);
            }
        });
        gameScreenPanel.add(playRoundButton);
        playRoundButton.setBounds(90, 30, 120, 30);

        playersList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(playersList);

        gameScreenPanel.add(jScrollPane2);
        jScrollPane2.setBounds(60, 110, 180, 310);

        playersLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playersLabel.setText("Players");
        gameScreenPanel.add(playersLabel);
        playersLabel.setBounds(110, 80, 80, 30);

        lowerLevelPanel.setBackground(new java.awt.Color(255, 255, 204));
        lowerLevelPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        roundNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roundNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundNoLabel.setText("Round Number:");

        movieTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        movieTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieTitleLabel.setText("Movie Title:");

        roundNoTextfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roundNoTextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        movieTitleTextfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        movieTitleTextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        playerAnswerSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerAnswerSubmitButton.setText("Submit Answer");
        playerAnswerSubmitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                playerAnswerSubmitButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                resetButtonActionPerformed(evt);
            }
        });

        name1Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name1Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name2Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name2Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name3Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name3Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name4Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name4Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name5Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name5Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name6Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name6Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name7Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name7Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name8Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name8Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name9Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name9Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name10Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name10Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name11Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name11Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name12Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name12Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name13Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name13Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name14Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name14Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name15Textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name15Textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("7.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("9.");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("10.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("11.");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("12.");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("13.");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("14.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("15.");

        javax.swing.GroupLayout lowerLevelPanelLayout = new javax.swing.GroupLayout(lowerLevelPanel);
        lowerLevelPanel.setLayout(lowerLevelPanelLayout);
        lowerLevelPanelLayout.setHorizontalGroup(
            lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                        .addComponent(roundNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(roundNoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name3Textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(name4Textfield)
                            .addComponent(name5Textfield)
                            .addComponent(name2Textfield)
                            .addComponent(name1Textfield))))
                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name9Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox9))
                            .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name7Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox7))
                            .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name8Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox8))
                            .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(playerAnswerSubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(name10Textfield))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox10))
                            .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name6Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox6)))
                        .addGap(32, 32, 32)
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                                .addComponent(resetButton)
                                .addGap(10, 10, 10))
                            .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(name15Textfield)
                                    .addComponent(name14Textfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name13Textfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name12Textfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name11Textfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jCheckBox11)
                                                .addContainerGap())
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createSequentialGroup()
                                                .addComponent(jCheckBox12)
                                                .addContainerGap()))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createSequentialGroup()
                                            .addComponent(jCheckBox13)
                                            .addContainerGap()))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBox15, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addContainerGap())))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(movieTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(movieTitleTextfield)
                        .addGap(15, 15, 15))))
        );
        lowerLevelPanelLayout.setVerticalGroup(
            lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roundNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movieTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundNoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movieTitleTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(name11Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox11)
                                    .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(name6Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(name1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))))
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox2)
                    .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(name2Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(name12Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel12))
                            .addComponent(jCheckBox7))
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name7Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jCheckBox8))
                        .addGroup(lowerLevelPanelLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(name8Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(name13Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))
                                    .addComponent(jCheckBox13))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(name3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))))
                .addGap(18, 18, 18)
                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(name14Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addComponent(jCheckBox14))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name4Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name9Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox4))
                .addGap(18, 18, 18)
                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(name15Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addComponent(jCheckBox15))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name5Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name10Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jCheckBox10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(lowerLevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerAnswerSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton))
                .addContainerGap())
        );

        gameScreenPanel.add(lowerLevelPanel);
        lowerLevelPanel.setBounds(250, 20, 790, 400);

        tablePanel.setBackground(new java.awt.Color(204, 204, 255));
        tablePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel16.setBackground(new java.awt.Color(0, 153, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Pos");

        jLabel17.setBackground(new java.awt.Color(0, 153, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Table");

        jLabel18.setBackground(new java.awt.Color(0, 153, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Name");

        jLabel19.setBackground(new java.awt.Color(0, 153, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Pts");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("1");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("2");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("3");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("4");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("5");

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("6");

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("7");

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("8");

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("9");

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("10");

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tablePanelLayout.createSequentialGroup()
                                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tablePanelLayout.createSequentialGroup()
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField22))
                                    .addGroup(tablePanelLayout.createSequentialGroup()
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField21))))
                            .addGroup(tablePanelLayout.createSequentialGroup()
                                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField29, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                    .addComponent(jTextField30)))
                            .addGroup(tablePanelLayout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField23))
                            .addGroup(tablePanelLayout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField24))
                            .addGroup(tablePanelLayout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField25))
                            .addGroup(tablePanelLayout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField26))
                            .addGroup(tablePanelLayout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField27))
                            .addGroup(tablePanelLayout.createSequentialGroup()
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField28))))
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gameScreenPanel.add(tablePanel);
        tablePanel.setBounds(1050, 20, 270, 440);

        updateTableSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateTableSubmitButton.setText("Update Table");
        updateTableSubmitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                updateTableSubmitButtonActionPerformed(evt);
            }
        });
        gameScreenPanel.add(updateTableSubmitButton);
        updateTableSubmitButton.setBounds(890, 430, 150, 30);

        jTabbedPane1.addTab("Game Screen", gameScreenPanel);

        SharedPanel.setPreferredSize(new java.awt.Dimension(1000, 200));

        messageArea.setColumns(20);
        messageArea.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        messageArea.setRows(5);
        messageArea.setMargin(new java.awt.Insets(2, 30, 2, 30));
        jScrollPane1.setViewportView(messageArea);

        javax.swing.GroupLayout SharedPanelLayout = new javax.swing.GroupLayout(SharedPanel);
        SharedPanel.setLayout(SharedPanelLayout);
        SharedPanelLayout.setHorizontalGroup(
            SharedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
        );
        SharedPanelLayout.setVerticalGroup(
            SharedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SharedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(SharedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE))
                .addContainerGap(460, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SharedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SharedPanel.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPlayerSubmitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addPlayerSubmitButtonActionPerformed
    {//GEN-HEADEREND:event_addPlayerSubmitButtonActionPerformed

        if (addPlayerTextField.getText().equals(""))
        {
            messageArea.setText("You must enter a name");
        }
        else
        {
            Player aPlayer = game.addPlayerToGame(addPlayerTextField.getText());
            //Result
            if (aPlayer == null)
            {
                messageArea.setText(addPlayerTextField.getText() + " can not be added because there are ten players in the game");
            }
            else
            {
                messageArea.setText(aPlayer.getName() + " has been added to the game");
                addPlayerTextField.setText("");
            }
        }
    }//GEN-LAST:event_addPlayerSubmitButtonActionPerformed

    private void addMovieSubmitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addMovieSubmitButtonActionPerformed
    {//GEN-HEADEREND:event_addMovieSubmitButtonActionPerformed
        
        if (addMovieTextField.getText().equals(""))
        {
            messageArea.setText("You must enter a movie title");
        }
        else
        {
            Movie aMovie = game.addMovieToGame(addMovieTextField.getText());
            //Result
            if (aMovie == null)
            {
                messageArea.setText(addMovieTextField.getText() + " can not be added because there are ten movies in the Game");
            }
            else
            {
                messageArea.setText(aMovie.getTitle() + " has been added to the game");
                addMovieTextField.setText("");
            }
        }
    }//GEN-LAST:event_addMovieSubmitButtonActionPerformed

    private void addActorToMovieSubmituttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addActorToMovieSubmituttonActionPerformed
    {//GEN-HEADEREND:event_addActorToMovieSubmituttonActionPerformed

        if ((actorsList.getSelectedValue() != null) && (moviesList.getSelectedValue() != null))
        {
            Actor theActor = (Actor)actorsList.getSelectedValue();
            Movie theMovie = (Movie)moviesList.getSelectedValue();
            Actor actor = game.addActorToMovie(theActor, theMovie);
            if (actor == null)
            {
                if (theMovie.getActors().size() == 12)
                {
                    JOptionPane.showMessageDialog(null, "12 actors are in movie. Unable to add another actor", "",
                        JOptionPane.INFORMATION_MESSAGE);
                } 
                else
                {
                    messageArea.setText(theActor + " is already in the movie");
                }
            }
            if (actor != null)
            {
                messageArea.setText(theActor + " is added to " + theMovie);
            }
        }
        else
        {
            messageArea.setText("You must select a movie and an actor");
        }
    }//GEN-LAST:event_addActorToMovieSubmituttonActionPerformed

    private void updateMoviesInGameButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_updateMoviesInGameButtonActionPerformed
    {//GEN-HEADEREND:event_updateMoviesInGameButtonActionPerformed
 
        moviesList.setListData(game.getMovies());
        messageArea.setText("List of movies in the game has been updated");
    }//GEN-LAST:event_updateMoviesInGameButtonActionPerformed

    private void displayPlayersInGameSubmitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_displayPlayersInGameSubmitButtonActionPerformed
    {//GEN-HEADEREND:event_displayPlayersInGameSubmitButtonActionPerformed
        messageArea.setText("");
        Collection<Player> players = game.getPlayers();
        if (players.isEmpty())
        {
            messageArea.setText("There are no players in the game");
        }
        else
        {
            for (Player eachPlayer : players)
            {
                messageArea.append(eachPlayer.getName() + "\n");
            }
        }
    }//GEN-LAST:event_displayPlayersInGameSubmitButtonActionPerformed

    private void displayActorsInMovieSubmitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_displayActorsInMovieSubmitButtonActionPerformed
    {//GEN-HEADEREND:event_displayActorsInMovieSubmitButtonActionPerformed
        messageArea.setText("");
        if (moviesList.getSelectedValue() == null)
        {
            messageArea.setText("You must select a movie");
        }
        else
        {
            Movie movie = (Movie)moviesList.getSelectedValue();
            Collection<Actor> actors = game.showActorsInMovie(movie);
            if (actors == null)
            {
                messageArea.setText("No actors in the movie");
            }
            else
            {
                for (Actor eachActor : actors)
                {
                    messageArea.append(eachActor.getName() + "\n");
                }
            }
        }
    }//GEN-LAST:event_displayActorsInMovieSubmitButtonActionPerformed

    private void initialiseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_initialiseSubmitButtonActionPerformed
    {//GEN-HEADEREND:event_initialiseSubmitButtonActionPerformed
        Boolean result = game.initialiseGame();
        String res = Boolean.toString(result);
        if (result)
        {
            messageArea.setText("The game is set to " + res + ". Go to Game screen tab and click on Play round button to start the game");
        }
        else
        {
            messageArea.setText("The game is set to " + res + ". You are unable to start the game");
        }
    }//GEN-LAST:event_initialiseSubmitButtonActionPerformed

    private void gameScreenPanelComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_gameScreenPanelComponentShown
    {//GEN-HEADEREND:event_gameScreenPanelComponentShown
        
        messageArea.setText("");
        
        playersList.setListData(game.getPlayers());
    }//GEN-LAST:event_gameScreenPanelComponentShown

    private void playRoundButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_playRoundButtonActionPerformed
    {//GEN-HEADEREND:event_playRoundButtonActionPerformed
        Boolean success = false;
        String[] array = {"","","","","","","","","","","","","","",""};
        Round round = game.playRound();

        if (game.getRounds().isEmpty() && game.getMovies().size() == 10)
        {
            messageArea.setText("");
            JOptionPane.showMessageDialog(null, "Thank you for playing", "",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else if (round == null)
        {
            messageArea.setText("Game must be initialised or table updated");
        }
        else
        {
            String movieTitle = round.getMovie().getTitle();
            movieTitleTextfield.setText(movieTitle);
            String roundNo = String.valueOf(round.getRoundNumber());
            roundNoTextfield.setText(roundNo);
            
            try
            {
                int count = 0;
                Collection<Actor> actors = round.get15Actors();

                for (Actor eachActor : actors)
                {
                    array[count] = eachActor.getName();
                    count ++;
                }
                success = true;
            }
            catch(ArrayIndexOutOfBoundsException exception)
            {
                JOptionPane.showMessageDialog(null, "Every player must have a turn before next round can be displayed", "",
                    JOptionPane.INFORMATION_MESSAGE);
            } 
            
            if (success)
            {
                messageArea.setText("This is Round " + roundNoTextfield.getText() + " of 10" + "\n");
                messageArea.append("Fifteen randomly selected actors are on display." + "\n");
                messageArea.append("Of these, some are in " + movieTitleTextfield.getText() + "\n\n");
                messageArea.append("Please choose wisely!");
                
                name1Textfield.setText(array[0]);
                name2Textfield.setText(array[1]);
                name3Textfield.setText(array[2]);
                name4Textfield.setText(array[3]);
                name5Textfield.setText(array[4]);

                name6Textfield.setText(array[5]);
                name7Textfield.setText(array[6]);
                name8Textfield.setText(array[7]);
                name9Textfield.setText(array[8]);
                name10Textfield.setText(array[9]);

                name11Textfield.setText(array[10]);
                name12Textfield.setText(array[11]);
                name13Textfield.setText(array[12]);
                name14Textfield.setText(array[13]);
                name15Textfield.setText(array[14]);
            }
        }
        
    }//GEN-LAST:event_playRoundButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resetButtonActionPerformed
    {//GEN-HEADEREND:event_resetButtonActionPerformed
        
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);
        jCheckBox12.setSelected(false);
        jCheckBox13.setSelected(false);
        jCheckBox14.setSelected(false);
        jCheckBox15.setSelected(false);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void playerAnswerSubmitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_playerAnswerSubmitButtonActionPerformed
    {//GEN-HEADEREND:event_playerAnswerSubmitButtonActionPerformed

        if ((playersList.getSelectedValue() == null) || (!game.getInitialised()) || (roundNoTextfield.getText().isEmpty()))
        {
            messageArea.setText("You must select a player, the game must be initialised and a round must be displayed");
        }
        else
        {
            Collection<String> checked = new HashSet<>();
        
            if (jCheckBox1.isSelected())
            {
                checked.add(name1Textfield.getText());
            }
            if (jCheckBox2.isSelected())
            {
                checked.add(name2Textfield.getText());
            }
            if (jCheckBox3.isSelected())
            {
                checked.add(name3Textfield.getText());
            }
            if (jCheckBox4.isSelected())
            {
                checked.add(name4Textfield.getText());
            }
            if (jCheckBox5.isSelected())
            {
                checked.add(name5Textfield.getText());
            }
            if (jCheckBox6.isSelected())
            {
                checked.add(name6Textfield.getText());
            }
            if (jCheckBox7.isSelected())
            {
                checked.add(name7Textfield.getText());
            }
            if (jCheckBox8.isSelected())
            {
                checked.add(name8Textfield.getText());
            }
            if (jCheckBox9.isSelected())
            {
                checked.add(name9Textfield.getText());
            }
            if (jCheckBox10.isSelected())
            {
                checked.add(name10Textfield.getText());
            }
            if (jCheckBox11.isSelected())
            {
                checked.add(name11Textfield.getText());
            }
            if (jCheckBox12.isSelected())
            {
                checked.add(name12Textfield.getText());
            }
            if (jCheckBox13.isSelected())
            {
                checked.add(name13Textfield.getText());
            }
            if (jCheckBox14.isSelected())
            {
                checked.add(name14Textfield.getText());
            }
            if (jCheckBox15.isSelected())
            {
                checked.add(name15Textfield.getText());
            }

            Player player = (Player)playersList.getSelectedValue();
            Round round = game.chooseRound();
            
            messageArea.setText("");
            Boolean result = game.playerAnswer(player, round, checked);
        
            if (result)
            {
                String name = playersList.getSelectedValue().toString();
                messageArea.setText(name + " has submitted the answer:" + "\n\n");
                for (String eachAnswer : checked)
                {
                    messageArea.append(eachAnswer + " ... ");
                }
            }
            else
            {
                messageArea.setText(playersList.getSelectedValue() + " is unable to submit answer again");
            }
        }
        
    }//GEN-LAST:event_playerAnswerSubmitButtonActionPerformed

    private void updateTableSubmitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_updateTableSubmitButtonActionPerformed
    {//GEN-HEADEREND:event_updateTableSubmitButtonActionPerformed
        
        if (game.getNumOfTurnsPerRound() != game.getPlayers().size() || (game.getPlayers().isEmpty()))
        {
            messageArea.setText("All players must play before table can be updated");
        }
        else
        {
            Movie movie = null;
            Round round = game.chooseRound();
            
            Integer[] table = game.updateTable(round);
            messageArea.setText("");
            
            Collection<Player> players = game.getPlayers();
            
            List<JTextField> names = new ArrayList<>();
            names.add(jTextField11);
            names.add(jTextField12);
            names.add(jTextField13);
            names.add(jTextField14);
            names.add(jTextField15);
            names.add(jTextField16);
            names.add(jTextField17);
            names.add(jTextField18);
            names.add(jTextField19);
            names.add(jTextField20);
            
            List<JTextField> points = new ArrayList<>();
            points.add(jTextField21);
            points.add(jTextField22);
            points.add(jTextField23);
            points.add(jTextField24);
            points.add(jTextField25);
            points.add(jTextField26);
            points.add(jTextField27);
            points.add(jTextField28);
            points.add(jTextField29);
            points.add(jTextField30);
            
            List<String> playersName = new ArrayList<>();
            
            messageArea.append("The actors in the movie " + movieTitleTextfield.getText() + " are:" + "\n\n"
             + round.getMovie().getActors() + "\n\n");
            
            int nameCount = 0;
            int pointCount = 0;
            for (Integer eachPoints : table)
            {
                String point = Integer.toString(eachPoints);
                points.get(pointCount).setText(point);
                pointCount ++;
                
                for (Player eachPlayer : players)
                {
                    String eachPlayersPoints = Integer.toString(eachPlayer.getPoints());
                    if (eachPlayersPoints.equals(point) && (!playersName.contains(eachPlayer.getName())))
                    {
                        names.get(nameCount).setText(eachPlayer.getName());
                        playersName.add(eachPlayer.getName());
                        nameCount ++;
                    } 
                }       
            }
            
            for(Player eachPlayer : game.getPlayers())
            {
                String pts = Integer.toString(eachPlayer.getPreviousScore());
                messageArea.append(eachPlayer.getName() + ":  Scored: " + pts + "\n\n");
            }   
        }
    }//GEN-LAST:event_updateTableSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MovieGameGUI.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MovieGameGUI.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MovieGameGUI.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MovieGameGUI.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MovieGameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SharedPanel;
    private m256gui.M256JList actorsList;
    private javax.swing.JButton addActorToMovieSubmitutton;
    private javax.swing.JLabel addMovieLabel;
    private javax.swing.JButton addMovieSubmitButton;
    private javax.swing.JTextField addMovieTextField;
    private javax.swing.JLabel addPlayerLabel;
    private javax.swing.JButton addPlayerSubmitButton;
    private javax.swing.JTextField addPlayerTextField;
    private javax.swing.JButton displayActorsInMovieSubmitButton;
    private javax.swing.JButton displayPlayersInGameSubmitButton;
    private javax.swing.JPanel gameScreenPanel;
    private javax.swing.JButton initialiseSubmitButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel listOfActorsLabel;
    private javax.swing.JPanel lowerLevelPanel;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JLabel movieTitleLabel;
    private javax.swing.JTextField movieTitleTextfield;
    private javax.swing.JLabel moviesInGameLabel;
    private m256gui.M256JList moviesList;
    private javax.swing.JTextField name10Textfield;
    private javax.swing.JTextField name11Textfield;
    private javax.swing.JTextField name12Textfield;
    private javax.swing.JTextField name13Textfield;
    private javax.swing.JTextField name14Textfield;
    private javax.swing.JTextField name15Textfield;
    private javax.swing.JTextField name1Textfield;
    private javax.swing.JTextField name2Textfield;
    private javax.swing.JTextField name3Textfield;
    private javax.swing.JTextField name4Textfield;
    private javax.swing.JTextField name5Textfield;
    private javax.swing.JTextField name6Textfield;
    private javax.swing.JTextField name7Textfield;
    private javax.swing.JTextField name8Textfield;
    private javax.swing.JTextField name9Textfield;
    private javax.swing.JButton playRoundButton;
    private javax.swing.JButton playerAnswerSubmitButton;
    private javax.swing.JLabel playersLabel;
    private m256gui.M256JList playersList;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel roundNoLabel;
    private javax.swing.JTextField roundNoTextfield;
    private javax.swing.JLabel setupLabel;
    private javax.swing.JPanel setupScreenPanel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton updateMoviesInGameButton;
    private javax.swing.JButton updateTableSubmitButton;
    // End of variables declaration//GEN-END:variables
}
